twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(ES_APP_NAME)%'
        app_name_description: '%env(ES_APP_CONTENT)%'
        app_contact: '%env(ES_MAILER_USER_MAIL)%'
        col_1_2: 'col-sm-12 col-md-12 col-lg-8'
        col_2_2: 'col-sm-12 col-md-12 col-lg-4'
        col_1_1: 'col-sm-12'
        row_lst: 'row row-cols-1 row-cols-md-2 row-cols-lg-3'
        col_sm_1_2: 'col-sm-12 col-md-12 col-lg-6 col-xl-3'
        col_sm_2_2: 'col-sm-12 col-md-12 col-lg-6 col-xl-9'