twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(ES_APP_NAME)%'
        app_name_description: '%env(ES_APP_CONTENT)%'
        app_contact: '%env(ES_MAILER_USER_MAIL)%'
        col_1_2: 'col-sm-12 col-md-12 col-lg-8'
        col_2_2: 'col-sm-12 col-md-12 col-lg-4'
        col_1_1: 'col-sm-12'
        row_lst: 'row row-cols-1 row-cols-md-2 row-cols-lg-3'
        col_sm_1_2: 'col-sm-12 col-md-12 col-lg-6 col-xl-3'
        col_sm_2_2: 'col-sm-12 col-md-12 col-lg-6 col-xl-9'
        news_time: '%env(ES_NEWS_TIME)%'
        liam_link: '%env(LIAM_LINK)%'
        liam_name: '%env(LIAM_NAME)%'
        es_contact_name: '%env(ES_CONTACT_NAME)%'
        es_contact_mail: '%env(ES_CONTACT_MAIL)%'
        es_contact_tel: '%env(ES_CONTACT_TEL)%'
        es_copyright: '%env(ES_COPYRIGHT)%'
        es_current_version: '%env(ES_CURRENT_VERSION)%'    
        es_mailer_smtp_host: '%env(ES_MAILER_SMTP_HOST)%'
        es_mailer_smtp_port: '%env(ES_MAILER_SMTP_PORT)%'
        es_mailer_user_name: '%env(ES_MAILER_USER_NAME)%'
        es_mailer_user_mail: '%env(ES_MAILER_USER_MAIL)%'
        es_tree_undevelopped_nbr: '%env(ES_TREE_UNDEVELOPPED_NBR)%'
        es_mailer_workflow_toresume: '%env(ES_MAILER_WORKFLOW_TORESUME)%'
        es_mailer_workflow_tovalidate: '%env(ES_MAILER_WORKFLOW_TOVALIDATE)%'
        es_mailer_workflow_tocontrol: '%env(ES_MAILER_WORKFLOW_TOCONTROL)%'
        es_mailer_workflow_tocheck: '%env(ES_MAILER_WORKFLOW_TOCHECK)%'
        es_mailer_workflow_published: '%env(ES_MAILER_WORKFLOW_PUBLISHED)%'
        es_mailer_workflow_torevise: '%env(ES_MAILER_WORKFLOW_TOREVISE)%'
        es_mailer_workflow_inreview: '%env(ES_MAILER_WORKFLOW_INREVIEW)%'           