# config/packages/workflow.yaml
framework:
    workflows:
        wkf_all:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'stateCurrent'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - toValidate
                - toControl
                - toCheck
                - toResume
                - published
                - abandonned
            transitions:
                goToValidate:
                    from: [draft, toResume]
                    to: toValidate
                goToControl:
                    from: toValidate
                    to: toControl 
                goToCheck:
                    from: toControl
                    to: toCheck
                goPublished:
                    from: toCheck
                    to: published                                   
                goToResume:
                    from: [published,toValidate, toControl, toCheck, abandonned]
                    to: toResume
                goAbandonned:
                    from: [published,toValidate, toControl, toCheck, draft, toResume]
                    to: abandonned
        wkf_without_doc:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'stateCurrent'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - toValidate
                - toControl                
                - toResume
                - published
                - abandonned
            transitions:
                goToValidate:
                    from: [draft, toResume]
                    to: toValidate  
                goToControl:
                    from: toValidate
                    to: toControl 
                goPublished:
                    from: toControl
                    to: published                                  
                goToResume:
                    from: [published, toValidate, toControl, abandonned]
                    to: toResume
                goAbandonned:
                    from: [published, toValidate, toControl, draft, toResume]
                    to: abandonned              
        wkf_without_control:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'stateCurrent'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - toValidate
                - toCheck
                - toResume
                - published
                - abandonned
            transitions:
                goToValidate:
                    from: [draft, toResume]
                    to: toValidate                
                goToResume:
                    from: [published, toValidate, toCheck, abandonned]
                    to: toResume
                goPublished:
                    from: toCheck
                    to: published
                goToCheck:
                    from: toValidate
                    to: toCheck                   
                goAbandonned:
                    from: [published, toValidate, toCheck, draft, toResume]
                    to: abandonned                 
        wkf_without_doccontrol:
            type: 'state_machine' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'stateCurrent'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - toValidate
                - toResume
                - published
                - abandonned
            transitions:
                goToValidate:
                    from: [draft, toResume]
                    to: toValidate                
                goToResume:
                    from: [published, toValidate, abandonned]
                    to: toResume
                goPublished:
                    from: toValidate
                    to: published                    
                goAbandonned:
                    from: [published, toValidate, draft, toResume]
                    to: abandonned




