App\Entity\Backpack:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [mProcess, process, category, name]
        errorPath: name
        message: 'Le nom du porte document "{{ value }}" est déjà déclaré dans cette arborescence.'
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 2
          max: 255
          minMessage: 'Le nom "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom "{{ value }}" ne peut pas avoir plus de 255 caractères'
    dir1:
      - Length:
          min: 2
          max: 100
          minMessage: 'Le nom du répertoire "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom du répertoire "{{ value }}" ne peut pas avoir plus de 100 caractères'
    dir2:
      - Length:
          min: 2
          max: 100
          minMessage: 'Le nom du répertoire "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom du répertoire "{{ value }}" ne peut pas avoir plus de 100 caractères'
    dir3:
      - Length:
          min: 2
          max: 100
          minMessage: 'Le nom du répertoire "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom du répertoire "{{ value }}" ne peut pas avoir plus de 100 caractères'
    dir4:
      - Length:
          min: 2
          max: 100
          minMessage: 'Le nom du répertoire "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom du répertoire "{{ value }}" ne peut pas avoir plus de 100 caractères'
    dir5:
      - Length:
          min: 2
          max: 100
          minMessage: 'Le nom du répertoire "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom du répertoire "{{ value }}" ne peut pas avoir plus de 100 caractères'